version: '3'

services:

  nginx:
    image: nginx:1.17.0-alpine
    restart: unless-stopped
    ports:
      - ${MIRROR_IPV4}:80:80/tcp
      - ${MIRROR_IPV6}:80:80/tcp
      - ${MIRROR_IPV4}:443:443/tcp
      - ${MIRROR_IPV6}:443:443/tcp
    volumes:
      - conf-nginx:/etc/nginx/conf.d
      - conf-certbot:/etc/letsencrypt
      - pub:/pub
      - www:/var/www

  # You will probably want this script to initialize LetsEncrypt: https://github.com/wmnnd/nginx-certbot/blob/master/init-letsencrypt.sh
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - conf-certbot:/etc/letsencrypt
      - www:/var/www
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  proftpd:
    image: instantlinux/proftpd
    restart: unless-stopped
    ports:
      - ${MIRROR_IPV4}:21:21
      - ${MIRROR_IPV6}:21:21
      - ${MIRROR_IPV4}:65484-65534:65484-65534
      - ${MIRROR_IPV6}:65484-65534:65484-65534
    volumes:
      - pub:/var/lib/ftp
    env_file: pasv_address.env
    environment:
      MAX_CLIENTS: 2000
      PASV_MIN_PORT: 65484
      PASV_MAX_PORT: 65534

  rsyncd:
    image: toendeavour/rsyncd-alpine
    restart: unless-stopped
    ports:
      - ${MIRROR_IPV4}:873:873
      - ${MIRROR_IPV6}:873:873
    volumes:
      - conf-rsyncd:/config
      - pub:/pub

volumes:
  conf-nginx:
    driver: n0r1skcom/docker-volume-cephfs:latest
    driver_opts:
      path: /conf/nginx
      name: ${CEPHFS_USER}
      secret: ${CEPHFS_SECRET}
      monitors: ${CEPHFS_MONS}
  conf-certbot:
    driver: n0r1skcom/docker-volume-cephfs:latest
    driver_opts:
      path: /conf/certbot
      name: ${CEPHFS_USER}
      secret: ${CEPHFS_SECRET}
      monitors: ${CEPHFS_MONS}
  conf-rsyncd:
    driver: n0r1skcom/docker-volume-cephfs:latest
    driver_opts:
      path: /conf/rsyncd
      name: ${CEPHFS_USER}
      secret: ${CEPHFS_SECRET}
      monitors: ${CEPHFS_MONS}
  pub:
    driver: n0r1skcom/docker-volume-cephfs:latest
    driver_opts:
      name: admin
      path: /pub
      name: ${CEPHFS_USER}
      secret: ${CEPHFS_SECRET}
      monitors: ${CEPHFS_MONS}
  www:
    driver: n0r1skcom/docker-volume-cephfs:latest
    driver_opts:
      name: admin
      path: /www
      name: ${CEPHFS_USER}
      secret: ${CEPHFS_SECRET}
      monitors: ${CEPHFS_MONS}
